version: '3.8'  # Docker Compose 파일 버전

services:  # 정의할 서비스
  java-app:  # 서비스 이름
    build: .  # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드
    ports:
      - "8080:8080"  # 호스트의 8080 포트를 컨테이너의 8080 포트에 매핑
    environment:
      - JAR_FILE=target/*.jar  # 컨테이너의 환경 변수 설정